<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class CreateBanlistSchema extends AbstractMigration
{
    public function up(): void
    {
        if ($this->getAdapter()->getAdapterType() !== 'pgsql') {
            throw new RuntimeException('CreateBanlistSchema requires the PostgreSQL adapter.');
        }

        $this->execute(<<<'SQL'
CREATE TABLE globalunsubscribe (
    gu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gu_suid VARCHAR(32) GENERATED ALWAYS AS (md5(gu_email)) STORED,
    gu_api VARCHAR(40) NOT NULL,
    gu_domain VARCHAR(253) NOT NULL,
    gu_dateunsubscribed TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gu_email VARCHAR(254) NOT NULL,
    gu_email_user VARCHAR(64) GENERATED ALWAYS AS (split_part(gu_email, '@', 1)) STORED,
    gu_email_domain VARCHAR(253) GENERATED ALWAYS AS (split_part(gu_email, '@', 2)) STORED,
    gu_type VARCHAR(20) NOT NULL,
    gu_reason VARCHAR(255) DEFAULT NULL,
    gu_active SMALLINT NOT NULL DEFAULT 1,
    CONSTRAINT uq_globalunsubscribe_email UNIQUE (gu_email),
    CONSTRAINT uq_globalunsubscribe_suid UNIQUE (gu_suid),
    CONSTRAINT chk_globalunsubscribe_type CHECK (
        gu_type IN ('ADMIN', 'BOUNCE', 'BOUNCE-ADMIN', 'INVALID', 'SPAM', 'SPAM-ADMIN', 'USER')
    ),
    CONSTRAINT chk_globalunsubscribe_active CHECK (gu_active IN (0, 1))
)
SQL);

        $this->execute('CREATE INDEX idx_globalunsubscribe_email_user_domain ON globalunsubscribe (gu_email_user, gu_email_domain)');
        $this->execute('CREATE INDEX idx_globalunsubscribe_email_domain ON globalunsubscribe (gu_email_domain)');
        $this->execute('CREATE INDEX idx_globalunsubscribe_reason ON globalunsubscribe (gu_reason)');
        $this->execute('CREATE INDEX idx_globalunsubscribe_type ON globalunsubscribe (gu_type)');
        $this->execute('CREATE INDEX idx_globalunsubscribe_active ON globalunsubscribe (gu_active)');

        $this->execute(<<<'SQL'
CREATE TABLE globaldomainunsubscribe (
    gdu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gdu_api VARCHAR(40) NOT NULL,
    gdu_domain VARCHAR(253) NOT NULL,
    gdu_dateunsubscribed TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gdu_domain_name VARCHAR(253) NOT NULL DEFAULT '',
    gdu_type VARCHAR(20) NOT NULL DEFAULT 'SPAM',
    gdu_active SMALLINT NOT NULL DEFAULT 1,
    CONSTRAINT uq_globaldomainunsubscribe_domain_name UNIQUE (gdu_domain_name),
    CONSTRAINT chk_globaldomainunsubscribe_type CHECK (gdu_type IN ('NOTEXIST', 'SPAM')),
    CONSTRAINT chk_globaldomainunsubscribe_active CHECK (gdu_active IN (0, 1))
)
SQL);

        $this->execute('CREATE INDEX idx_globaldomainunsubscribe_active ON globaldomainunsubscribe (gdu_active)');
    }

    public function down(): void
    {
        if ($this->getAdapter()->getAdapterType() !== 'pgsql') {
            throw new RuntimeException('CreateBanlistSchema requires the PostgreSQL adapter.');
        }

        $this->execute('DROP TABLE IF EXISTS globaldomainunsubscribe');
        $this->execute('DROP TABLE IF EXISTS globalunsubscribe');
    }
}
