<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class CreateCoreApplicationSchema extends AbstractMigration
{
    public function up(): void
    {
        if ($this->getAdapter()->getAdapterType() !== 'pgsql') {
            throw new RuntimeException('CreateCoreApplicationSchema requires the PostgreSQL adapter.');
        }

        $this->execute(<<<'SQL'
CREATE TABLE archives (
    a_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    a_subject VARCHAR(200) DEFAULT NULL,
    a_html TEXT,
    a_datecreated TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    a_viewed INTEGER NOT NULL DEFAULT 0
)
SQL);

        $this->execute(<<<'SQL'
CREATE TABLE templates (
    t_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    t_name VARCHAR(100) DEFAULT NULL,
    t_html TEXT,
    t_text TEXT
)
SQL);

        $this->execute(<<<'SQL'
CREATE TABLE options (
    o_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    o_key VARCHAR(100) NOT NULL,
    o_value VARCHAR(255) DEFAULT NULL,
    CONSTRAINT uq_options_key UNIQUE (o_key)
)
SQL);

        $this->execute(<<<'SQL'
CREATE TABLE subscribers (
    s_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_email VARCHAR(254) NOT NULL,
    s_email_user VARCHAR(64) GENERATED ALWAYS AS (split_part(s_email, '@', 1)) STORED,
    s_email_domain VARCHAR(253) GENERATED ALWAYS AS (split_part(s_email, '@', 2)) STORED,
    s_uniqid VARCHAR(32) GENERATED ALWAYS AS (md5(s_email)) STORED,
    s_last_interacted TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    s_priority INTEGER NOT NULL DEFAULT 0,
    s_subscribedate TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    s_subscribedby VARCHAR(50) NOT NULL DEFAULT 'SELF',
    s_confirm SMALLINT NOT NULL DEFAULT 0,
    s_confirmdate TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    s_unsubscribe SMALLINT NOT NULL DEFAULT 0,
    s_unsubscribedate TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    s_unsubscribereason VARCHAR(100) DEFAULT NULL,
    s_bounces INTEGER DEFAULT 0,
    s_emailsleft INTEGER NOT NULL DEFAULT 0,
    s_fname VARCHAR(50) DEFAULT NULL,
    s_lname VARCHAR(50) DEFAULT NULL,
    s_province VARCHAR(30) DEFAULT NULL,
    s_country VARCHAR(30) DEFAULT NULL,
    s_gender VARCHAR(30) DEFAULT NULL,
    CONSTRAINT uq_subscribers_email UNIQUE (s_email),
    CONSTRAINT uq_subscribers_uniqid UNIQUE (s_uniqid)
)
SQL);
        $this->execute('CREATE INDEX idx_subscribers_confirm ON subscribers (s_confirm)');
        $this->execute('CREATE INDEX idx_subscribers_email_user ON subscribers (s_email_user)');
        $this->execute('CREATE INDEX idx_subscribers_email_domain ON subscribers (s_email_domain)');
        $this->execute('CREATE INDEX idx_subscribers_last_interacted ON subscribers (s_last_interacted)');
        $this->execute('CREATE INDEX idx_subscribers_priority ON subscribers (s_priority)');
        $this->execute('CREATE INDEX idx_subscribers_unsubscribe ON subscribers (s_unsubscribe)');

        $this->execute(<<<'SQL'
CREATE TABLE messages (
    m_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    m_uniqid VARCHAR(32) DEFAULT NULL,
    m_t_id INTEGER NOT NULL DEFAULT 0,
    m_from_name VARCHAR(100) DEFAULT NULL,
    m_from_address VARCHAR(254) DEFAULT NULL,
    m_subject VARCHAR(200) DEFAULT NULL,
    m_priority INTEGER NOT NULL DEFAULT 0,
    m_listname VARCHAR(50) NOT NULL DEFAULT 'ALL',
    m_html TEXT,
    m_text TEXT,
    m_datesent TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    m_queued INTEGER NOT NULL DEFAULT 0,
    m_sent INTEGER NOT NULL DEFAULT 0,
    m_max_send INTEGER NOT NULL DEFAULT 0,
    m_reads INTEGER NOT NULL DEFAULT 0,
    m_last_read TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    m_likes INTEGER NOT NULL DEFAULT 0,
    m_last_like TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    m_dislikes INTEGER NOT NULL DEFAULT 0,
    m_last_dislike TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    m_bounces INTEGER DEFAULT 0,
    m_a_id INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_messages_uniqid UNIQUE (m_uniqid)
)
SQL);
        $this->execute('CREATE INDEX idx_messages_archive_id ON messages (m_a_id)');

        $this->execute(<<<'SQL'
CREATE TABLE queue (
    q_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    q_muid VARCHAR(32) NOT NULL,
    q_subject VARCHAR(200) DEFAULT NULL,
    q_suid VARCHAR(32) NOT NULL,
    q_email VARCHAR(254) NOT NULL,
    q_listname VARCHAR(50) NOT NULL DEFAULT '',
    q_date_added TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    q_last_interacted TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    q_mpriority INTEGER NOT NULL DEFAULT 0,
    q_spriority INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_queue_muid_suid UNIQUE (q_muid, q_suid)
)
SQL);
        $this->execute('CREATE INDEX idx_queue_default ON queue (q_mpriority DESC, q_last_interacted DESC, q_spriority DESC, q_id ASC)');
        $this->execute('CREATE INDEX idx_queue_priority ON queue (q_mpriority DESC, q_last_interacted DESC, q_spriority DESC)');

        $this->execute(<<<'SQL'
CREATE TABLE sendlog (
    sl_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sl_muid VARCHAR(32) NOT NULL DEFAULT '',
    sl_datesent TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sl_type VARCHAR(20) NOT NULL,
    sl_email VARCHAR(254) NOT NULL DEFAULT '',
    sl_suid VARCHAR(32) GENERATED ALWAYS AS (md5(sl_email)) STORED,
    sl_listname VARCHAR(50) NOT NULL DEFAULT '',
    sl_subject VARCHAR(200) NOT NULL DEFAULT ''
)
SQL);
        $this->execute('CREATE INDEX idx_sendlog_type ON sendlog (sl_type)');
        $this->execute('CREATE INDEX idx_sendlog_email ON sendlog (sl_email)');
        $this->execute('CREATE INDEX idx_sendlog_datesent ON sendlog (sl_datesent)');

        $this->execute(<<<'SQL'
CREATE TABLE sitelog (
    sl_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sl_email VARCHAR(254) DEFAULT NULL,
    sl_url VARCHAR(253) DEFAULT NULL,
    sl_ip VARCHAR(45) DEFAULT NULL,
    sl_host VARCHAR(253) DEFAULT NULL,
    sl_xfwdfor VARCHAR(45) DEFAULT NULL,
    sl_agent VARCHAR(254) DEFAULT NULL,
    sl_logged_in SMALLINT NOT NULL DEFAULT 0,
    sl_logged_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
SQL);
        $this->execute('CREATE INDEX idx_sitelog_logged_at ON sitelog (sl_logged_at)');

        $this->execute(<<<'SQL'
CREATE TABLE smlog (
    sml_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sml_suid VARCHAR(32) NOT NULL,
    sml_email VARCHAR(254) NOT NULL,
    sml_listname VARCHAR(50) DEFAULT '',
    sml_muid VARCHAR(32) NOT NULL,
    sml_date_added TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sml_date_sent TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_reads INTEGER NOT NULL DEFAULT 0,
    sml_last_read TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_likes INTEGER NOT NULL DEFAULT 0,
    sml_last_like TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_dislikes INTEGER NOT NULL DEFAULT 0,
    sml_last_dislike TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_updates INTEGER NOT NULL DEFAULT 0,
    sml_last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_confirms INTEGER NOT NULL DEFAULT 0,
    sml_confirmed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_forwards INTEGER NOT NULL DEFAULT 0,
    sml_last_forwarded TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_bookings INTEGER NOT NULL DEFAULT 0,
    sml_last_booking TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_subscribe SMALLINT NOT NULL DEFAULT 0,
    sml_subscribed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    sml_unsubscribe SMALLINT NOT NULL DEFAULT 0,
    sml_unsubscribed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    CONSTRAINT uq_smlog_suid_muid UNIQUE (sml_suid, sml_muid)
)
SQL);
        $this->execute('CREATE INDEX idx_smlog_suid ON smlog (sml_suid)');
        $this->execute('CREATE INDEX idx_smlog_muid ON smlog (sml_muid)');

        $this->execute(<<<'SQL'
CREATE TABLE users (
    u_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    u_uniqid VARCHAR(32) NOT NULL,
    u_identifier VARCHAR(100) NOT NULL,
    u_session_token VARCHAR(100) DEFAULT NULL,
    u_email VARCHAR(254) DEFAULT NULL,
    u_suid VARCHAR(32) GENERATED ALWAYS AS (md5(u_email)) STORED,
    u_username VARCHAR(100) DEFAULT NULL,
    u_password VARCHAR(100) DEFAULT NULL,
    u_last_login TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    u_ip VARCHAR(100) DEFAULT NULL,
    u_xfwdfor VARCHAR(100) DEFAULT NULL,
    u_admin SMALLINT NOT NULL DEFAULT 0,
    u_provider VARCHAR(100) DEFAULT NULL,
    u_fname VARCHAR(100) DEFAULT NULL,
    u_lname VARCHAR(100) DEFAULT NULL,
    u_gender VARCHAR(30) DEFAULT NULL,
    u_birthday VARCHAR(10) DEFAULT NULL,
    u_url VARCHAR(253) DEFAULT NULL,
    u_phone VARCHAR(20) DEFAULT NULL,
    u_photo VARCHAR(253) DEFAULT NULL,
    u_business VARCHAR(100) DEFAULT NULL,
    u_province VARCHAR(100) DEFAULT '',
    u_country VARCHAR(100) DEFAULT NULL,
    CONSTRAINT uq_users_uniqid UNIQUE (u_uniqid),
    CONSTRAINT uq_users_identifier UNIQUE (u_identifier),
    CONSTRAINT uq_users_session_token UNIQUE (u_session_token)
)
SQL);
    }

    public function down(): void
    {
        if ($this->getAdapter()->getAdapterType() !== 'pgsql') {
            throw new RuntimeException('CreateCoreApplicationSchema requires the PostgreSQL adapter.');
        }

        foreach ([
            'smlog',
            'sitelog',
            'sendlog',
            'queue',
            'messages',
            'users',
            'subscribers',
            'options',
            'templates',
            'archives',
        ] as $table) {
            $this->execute(sprintf('DROP TABLE IF EXISTS %s', $table));
        }
    }
}
