[globals]
; TODO: move most this config to db table
Organisation = "org_name"
Telephone = "org_tel"
WhatsApp = "org_whatsapp"
WhatsAppURL = "https://wa.me/27org_whatsapp"
StreetAddress = "org_addr"
ListName = "name_of_list"
API = "random_api_id"
Domain = "domain_name"

; define the url of your installation. include a / at the end
BaseURL = "https://domain_name/"

; 1 = automatically create archive, 0 = no archive (default)
archive = 0

; the {advertise} global template placeholder is replaced by this url
AdvertiseURL = ""
FacebookPageURL = ""
TwitterURL = ""
;BookingURL = "booking-form"
;ContactURL = "contact-form"
BookingURL = "{BaseURL}booking-form/{suid}/{muid}"
ContactURL = "{BaseURL}contact-form/{suid}/{muid}"
	
OrderEmail = "bookings@domain_name"
OrderFormName = "NAME booking form"
OrderFormSubject = "Your booking for NAME has been received"
OrderLogFilename = "name.txt"

; notifications and test messages get sent to this address
AdminName = "NAME Admin"
AdminEmail = "admin@domain_name"
	
;no longer used
TestEmail = "[EMAIL]"

; the from name and address is used when sending messages to the list
FromName = "From_name"
FromAddress = "info@domain_name"

; no longer used
from_addresses[0] = "info@domain_name"
from_addresses[1] = "noreply@domain_name"
	
; This is an implementation of a new system which requires all subscribers to periodically re-confirm their subscription
SubscriptionMessage = "Would you like to continue receiving our emails? {confirm} | To cancel your subscription {unsubscribe}"
SubscriptionConfirmMessage = "Your subscription is coming to an end soon. To continue receiving our emails, please {confirm} or cancel {unsubscribe}"

; Level at which the subscriber will be shown the ConfirmMessage
SubscriptionConfirmLevel = 2
; The number of emails the subscriber will set their subscription to when they re-confirm. Each time an email is sent, the number of emails remaining to be sent to them is decremented
SubscriptionConfirmAmount = 10

BounceAddress = "noreply-bounce@domain_name"
; set this higher to be more tolerant of bounces or lower to be less
BounceLimit = 2

UnsubscribeAddress = "noreply-unsubscribe@domain_name"

; array of SMTP servers to use in order of their listing for sending queued mail.
smtp_servers[0].active = 1
smtp_servers[0].name = "local"
smtp_servers[0].host = "localhost"
smtp_servers[0].port = 25
smtp_servers[0].enc = ""
smtp_servers[0].user = "user_name"
smtp_servers[0].pass = "user_pass"
smtp_servers[0].sendrate = 13
smtp_servers[0].batchsize = 800
smtp_servers[0].delay = 30

; local smtp server is used for sending notifications and test sends
default_smtp_server.active = 1
default_smtp_server.name = "local"
default_smtp_server.host = "localhost"
default_smtp_server.port = 25
default_smtp_server.enc = ""
default_smtp_server.user = "user_name"
default_smtp_server.pass = "user_pass"

; rate of SMTP sending
EmailsPerMinute = 13

; database connection variables
dbhost = "localhost"
dbuser = "user_name"
dbpass = "user_pass"
dbname = "db_name"
