[globals]
pclass = "d-inline-flex p-2 border-info bg-light"

;form classes
fieldsetclass = "mb-3"

rowclass = "row"

;columnclass = "form-floating mb-3 py-2 col-md-6"
;columnclass2 = "form-floating mb-3 py-2 col-md-12"
;columnclass3 = "form-floating mb-3 py-2 col-md-4"
;columnclass4 = "form-floating mb-3 py-2 col-md-2"
;columnclass5 = "form-floating mb-3 py-2 col-md-3"

columnclass1 = "form-floating mb-3 py-2 col-md-1"
columnclass2 = "form-floating mb-3 py-2 col-md-2"
columnclass3 = "form-floating mb-3 py-2 col-md-3"
columnclass4 = "form-floating mb-3 py-2 col-md-4"
columnclass5 = "form-floating mb-3 py-2 col-md-5"
columnclass6 = "form-floating mb-3 py-2 col-md-6"
columnclass7 = "form-floating mb-3 py-2 col-md-7"
columnclass8 = "form-floating mb-3 py-2 col-md-8"
columnclass9 = "form-floating mb-3 py-2 col-md-9"
columnclass10 = "form-floating mb-3 py-2 col-md-10"
columnclass11 = "form-floating mb-3 py-2 col-md-11"
columnclass12 = "form-floating mb-3 py-2 col-md-12"

;labelclass = "col-form-label p-2 text-white g-bg-aqua"

labelclass = ""

selectclass = "form-select"

inputclass = "form-control"

checkdivclass = "form-check"
checkclass = "form-check-input"
checklabelclass = "form-check-label"

textareaclass = "form-control"
textareawidth = "1275"
textareawidth2 = "600"
textareaheight = "900"
textareaheight2 = "450"

buttonclass = "btn btn-lg btn-primary"

;table classes
tableresponsive = "table-responsive"
tableclass = "table table-bordered table-hover table-striped u-table--v2 g-col-border-side-0"
theadclass = "text-uppercase g-letter-spacing-1"
tbodyclass = "g-font-size-12 g-color-black-opacity-0_6 g-font-weight-600"
trclass = "g-bg-primary g-color-white g-col-border-top-0"
thclass = "g-brd-white-opacity-0_1"
thclasscenter = "text-center g-brd-white-opacity-0_1"
tdclass = "text-center align-middle"
paginatediv = "d-flex flex-row justify-content-between"
